In [2]:
# Classsification of Machine Learning

print("Hi Ns Loni Good Morning") 
print("Hello Comes to ML Learning")

Hi Ns Loni Good Morning
Hello Comes to ML Learning


In [5]:
# For Example
# OR gate

# x,y is input   and   w is output
# 1

import numpy as np
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,1])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [6]:
y

array([0, 1, 1, 1])

In [7]:
# conditions

w = np.array([1,1])
w

array([1, 1])

In [13]:
b = -0.5

In [17]:
pred = []
for a in x:
    y_hat = np.dot(a,w)+b
    pred.append(activation(y_hat))

In [18]:
pred

[0, 1, 1, 1]

In [15]:
def activation(z):
    if z>0:
        return 1
    else:
        return 0

In [19]:
# 2 Classification Working

# PERCEPTION LEARNING

import math
import numpy as np

In [20]:
epochs = 100
alpha = 0.2

In [25]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()

print("Initial Weigth")

print("w0 = ",w0,"w1= ",w1,"w2= ",w2)

Initial Weigth
w0 =  0.18008285914911604 w1=  0.9313037120869033 w2=  0.7179502734662963


In [26]:
del_w0 = 1
del_w2 = 1
del_w1 = 1

In [27]:
train_data_temp = [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]

train_data = np.asarray(train_data_temp)
op = np.array([0,1,1,1,1,1,1,1])

In [28]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [29]:
op 

array([0, 1, 1, 1, 1, 1, 1, 1])

In [33]:
# y = (x*w) + b

bias = 0

for i in range(epochs):
    j = 0
    for x in train_data:
        y_hat = w0*x[0] + w1*x[1] + w2*x[2] + bias

        if(y_hat > 0):
            act = 1
        else:
            act = 0

        err = op[j] - act

        del_w0 = alpha*x[0]*err
        del_w1 = alpha*x[1]*err
        del_w2 = alpha*x[2]*err

        w0  = w0 + del_w0
        w1  = w1 + del_w1
        w2  = w2 + del_w2

        j = j+1
        print("epoch",i+1,"error= ",err)
        print(del_w0, del_w1, del_w2)

epoch 1 error=  0
0.0 0.0 0.0
epoch 1 error=  0
0.0 0.0 0.0
epoch 1 error=  0
0.0 0.0 0.0
epoch 1 error=  0
0.0 0.0 0.0
epoch 1 error=  0
0.0 0.0 0.0
epoch 1 error=  0
0.0 0.0 0.0
epoch 1 error=  0
0.0 0.0 0.0
epoch 1 error=  0
0.0 0.0 0.0
epoch 2 error=  0
0.0 0.0 0.0
epoch 2 error=  0
0.0 0.0 0.0
epoch 2 error=  0
0.0 0.0 0.0
epoch 2 error=  0
0.0 0.0 0.0
epoch 2 error=  0
0.0 0.0 0.0
epoch 2 error=  0
0.0 0.0 0.0
epoch 2 error=  0
0.0 0.0 0.0
epoch 2 error=  0
0.0 0.0 0.0
epoch 3 error=  0
0.0 0.0 0.0
epoch 3 error=  0
0.0 0.0 0.0
epoch 3 error=  0
0.0 0.0 0.0
epoch 3 error=  0
0.0 0.0 0.0
epoch 3 error=  0
0.0 0.0 0.0
epoch 3 error=  0
0.0 0.0 0.0
epoch 3 error=  0
0.0 0.0 0.0
epoch 3 error=  0
0.0 0.0 0.0
epoch 4 error=  0
0.0 0.0 0.0
epoch 4 error=  0
0.0 0.0 0.0
epoch 4 error=  0
0.0 0.0 0.0
epoch 4 error=  0
0.0 0.0 0.0
epoch 4 error=  0
0.0 0.0 0.0
epoch 4 error=  0
0.0 0.0 0.0
epoch 4 error=  0
0.0 0.0 0.0
epoch 4 error=  0
0.0 0.0 0.0
epoch 5 error=  0
0.0 0.0 0.0
epoch 5 er

In [ ]:
# Technical Terms

