In [6]:
# SVM Classifier

from sklearn import svm

from sklearn import datasets

In [7]:
iris = datasets.load_iris()

In [8]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
x = iris.data[:,2]

In [14]:
y = iris.target

In [47]:
from sklearn.model_selection import train_test_split
# Now you can use train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [43]:
x_train, x_test,y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=4)

In [20]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [22]:
from sklearn.model_selection import train_test_split

In [24]:
from sklearn.model_selection import train_test_split
# Now you can use train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [31]:
x_train_mod = x_train.reshape(-1,1)

In [49]:
x_test_mod = x_test.reshape(-1,1)

In [33]:
y_train_mod = y_train.reshape(-1,1)

In [48]:
y_test_mod = y_test.reshape(-1,1)

In [35]:
model = svm.SVC(kernel = 'linear')

In [50]:
model.fit(x_train_mod, y_train_mod)

#hist_mobilenet = mobilenet1.fit(train_gen, validation_data=val_gen, epochs=1)

C:\Users\nagar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [51]:
y_pred_mod = model.predict(x_test_mod)

In [39]:
from sklearn.metrics import accuracy_score

In [58]:
print(accuracy_score(y_test_mod, y_pred_mode))



NameError: name 'y_pred_mode' is not defined

In [ ]:
# Output:  0.966666666666666666666667

In [ ]:
# K-Nearest Neighbors----[or]---------KNN

In [59]:
from sklearn.datasets import load_iris

iris = load_iris()

In [60]:
x = iris.data
y = iris.target

In [61]:
x.shape

(150, 4)

In [62]:
y.shape

(150,)

In [63]:
from sklearn.neighbors import KNeighborsClassifier

In [64]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn

KNeighborsClassifier(n_neighbors=1)

In [65]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=1)

In [67]:
# knn.predict([4,5,6,2])

# Reshape your data either using array.reshape(-1, 1) if 
# your data has a single feature
# or array.reshape(1, -1) if it contains a single sample.

In [68]:
import numpy as np
a = np.array([4,5,6,2])
a.shape

(4,)

In [69]:
knn.predict([a])

array([2])